# shellcheck shell=bash disable=SC2034  # SECRETS is used by the scripts that source this
# Shared by deploy/init, up, down and check (sourced from the project root).

# Every secret of the deploy profile: generated by deploy/init into deploy/.env, checked by deploy/up.
SECRETS=(PROVIDER_API_KEY CONSUMER_API_KEY IDENTITYHUB_SUPERUSER_KEY ISSUER_SUPERUSER_KEY EDC_DB_PASSWORD
    VAULT_TOKEN_ISSUERSERVICE VAULT_TOKEN_PROVIDER_IDENTITYHUB VAULT_TOKEN_PROVIDER_CONTROLPLANE
    VAULT_TOKEN_PROVIDER_DATAPLANE VAULT_TOKEN_CONSUMER_IDENTITYHUB VAULT_TOKEN_CONSUMER_CONTROLPLANE
    VAULT_TOKEN_CONSUMER_DATAPLANE)

# compose <args>: the hosted data space. The learning stack (compose.template.yaml) with the deploy
# changes on top (deploy/compose.yaml); no dev container, no profile (so no Gaia-X mock).
# vault-seed runs as you (DEPLOY_UID/GID), so it can write deploy/secrets/.
compose() {
    COMPOSE_PROFILES="" DEPLOY_UID="$(id -u)" DEPLOY_GID="$(id -g)" docker compose -p "$(basename "$PWD")-deploy" --env-file deploy/.env \
        -f compose.template.yaml -f deploy/compose.yaml "$@"
}
